opFile=open('first.txt','w')
opFile.write('hello this is a test\npython file handling is pretty easy\nthis is our 6th sem')
opFile.close()
print("DATA BEFORE APPENDING\n")
rFile=open('first.txt','r')
lines=rFile.read()
print(lines,end="")
rFile.close()
print("\n\nDATA AFTER APPENDING\n")
opFile=open('first.txt','a')
opFile.write('\nthis is appended data!!!!!')
opFile.close()
opFile=open('first.txt','r')
print(opFile.read())
opFile.close()